### ISSUE TITLE
What are preferred braille sizes in mm?

### ISSUE THREAD

**Issue by smithdtyler** [tactile-graphics/guides#3]
@funkonaut what did your tests find for preferred braille dot spacing? In 2100752080fa43de58d8491eed508f42cc575173 you mentioned 35-37 pt size, but I am not sure how that translates to measured size.  

Phrasing the question differently, for the tested 35 pt font, what is the diameter of each dot? What is the center-to-center spacing of the closest dots? 

Here's how I am interpreting the names of the measured distances:

<img width="612" alt="Annotated picture of braille T with notes for dimension names." src="https://user-images.githubusercontent.com/8142684/154848105-7b56ef15-e661-41fe-8790-8f2989db38d0.png">

[This page](http://www.brailleauthority.org/sizespacingofbraille/sizespacingofbraille.pdf) recommends

> 3.2.1 The nominal height of braille dots shall be 0.019 inches [0.48 mm] and shall be
> uniform within any given transcription.
> 3.2.2 The nominal base diameter of braille dots shall be 0.057 inches [1.44 mm].
> 3.2.3 Cell spacing of dots shall conform to the following:
> 3.2.3.1 The nominal distance from center to center of adjacent dots (horizontally
> or vertically, but not diagonally) in the same cell shall be 0.092 inches
> [2.340 mm].
> 3.2.3.2 The nominal distance from center to center of corresponding dots in
> adjacent cells shall be 0.245 inches [6.2 mm].

**Comment by funkonaut** [comment]
[Updated dimensions](https://github.com/tactile-graphics/guides/wiki/Braille)
[Updated design doc](https://github.com/tactile-graphics/guides/wiki/Design-Considerations#braille-size-and-font)

**Comment by smithdtyler** [comment]
Perfect, thanks!
